# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_HACKAGE_REVISION=1

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Class of filtrable containers"
HOMEPAGE="https://github.com/strake/filtrable.hs"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+containers"

RDEPEND=">=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/smallcheck-1.2 <dev-haskell/smallcheck-1.3
		>=dev-haskell/tasty-1.3.1 <dev-haskell/tasty-1.4
		>=dev-haskell/tasty-smallcheck-0.8.1 <dev-haskell/tasty-smallcheck-0.9 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag containers containers)
}
