# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Half-precision floating-point"
HOMEPAGE="https://github.com/ekmett/half"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

CABAL_CHDEPS=(
	'deepseq >=1.3.0.0 && <1.5' 'deepseq >= 1.3.0.0'
)

RDEPEND=">=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/quickcheck-2.14.1 <dev-haskell/quickcheck-2.15
		dev-haskell/test-framework
		dev-haskell/test-framework-quickcheck2 )
"
